token: "lip_00g6etapIoYYzfXXzL6I"    # lichess OAuth2 Token
url: "https://lichess.org/"  # lichess base URL

engine:                      # engine settings
  dir: "./engines/"          # dir containing engines, relative to this project
  name: "sf"        # binary name of the engine to use
  variantname: "vsf"

abort_time: 20               # time to abort a game in seconds when there is no activity
rate_limiting_delay: 0       # time (in ms) to delay after sending a move to prevent "Too Many Requests" errors

challenge:                   # incoming challenges
  accept_bot: true          # accepts challenges coming from other bots
  max_increment: 5         # maximum amount of increment to accaept a challenge. the max is 180. set to 0 for no increment
  min_increment: 0           # minimum amount of increment to accept a challenge
  variants:                  # chess variants to accept (http://lichess.org/variant)
 #   - standard
#   - fromPosition
#    - antichess
#    - atomic
#    - chess960
#    - crazyhouse
#    - horde
#    - kingOfTheHill
#    - racingKings
#    - threeCheck
  time_controls:             # time controls to accept
#    - bullet
#    - blitz
#    - rapid
 #   - classical
#    - correspondence
  modes:                     # game modes to accept
 #   - casual                 # unrated games
 #   - rated                  # rated games - must comment if the engine doesn't try to win
 greeting:
    # Optional substitution keywords (include curly braces):
    #   {opponent} to insert opponent's name
    #   {me} to insert bot's name
    hello: "Hello I am @{me}! !This bot is made by @Soloboy4! Best of luck @{opponent} .  Type !help for a list of commands I can respond to." # Message to send to chat at the start of a game
    hello: "Hmm good move it's looking like it would be a long game!"#Message to send to chat after 50 moves done on the game
    hello:"The game is going good!"#Message to send to chat after 100 moves done on the game
    goodbye: "That was a beautiful game !Hope we meet soon again  on a game @{opponent}" # Message to send to chat at the end of a game if the game is won
    goodbye:"Hmm this time I Lose but next time I will surely try to beat you!"#Message to send to chat at the end of the game if the game is losed
    goodbye:"Hmm this time draw but I hope next time we get an perfect result of game!"#Message to send to chat at the end of the game if the game is draw

